version: '3'

services:
  api:
    build: .
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      - db
    container_name: api
    environment:
      - DB_STRING=mongodb://api-db:27017/${DB_NAME}
      - SECRET=${SECRET}
      - PORT=${PORT}
      - HOST=0.0.0.0
      - ADMIN_USER=${ADMIN_USER}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}

  db:
    image: mongo
    ports:
      - '27017:27017'
    container_name: api-db
